server:
  port: 8080

spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/uiqun?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3000
  
mybatis:
  type-aliases-package: com.uiqun.model
  mapper-locations: classpath:/xml/*.xml