server:
  port: 80

spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/uiqun?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 3000
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb

mybatis:
  type-aliases-package: com.uiqun.model
  mapper-locations: classpath:/xml/*.xml
